Repository aleph-im/aleph-vm, pull requests merged in 2023-12, with the labels that each got.

#490 QEmu support continuation
  .github/workflows/test-new-runtime-examples.yml
  .github/workflows/test-on-droplets-matrix.yml
  docker/vm_supervisor-dev.dockerfile
  examples/qemu_message_from_aleph.json
  examples/volumes/Dockerfile
  packaging/Makefile
  packaging/aleph-vm/DEBIAN/control
  pyproject.toml
  src/aleph/vm/conf.py
  src/aleph/vm/controllers/firecracker/executable.py
  src/aleph/vm/controllers/firecracker/instance.py
  src/aleph/vm/controllers/firecracker/program.py
  src/aleph/vm/controllers/firecracker/snapshot_manager.py
  src/aleph/vm/controllers/interface.py
  src/aleph/vm/controllers/qemu/QEMU.md
  src/aleph/vm/controllers/qemu/__init__.py
  src/aleph/vm/controllers/qemu/cloudinit.py
  src/aleph/vm/controllers/qemu/instance.py
  src/aleph/vm/hypervisors/firecracker/microvm.py
  src/aleph/vm/models.py
  src/aleph/vm/orchestrator/README.md
  src/aleph/vm/orchestrator/cli.py
  src/aleph/vm/orchestrator/views/operator.py
  src/aleph/vm/pool.py
Labels: BLACK

#496 Problem: Log system won't work when we switch to systemd
  packaging/aleph-vm/DEBIAN/control
  pyproject.toml
  src/aleph/vm/controllers/firecracker/executable.py
  src/aleph/vm/controllers/qemu/instance.py
  src/aleph/vm/orchestrator/views/operator.py
Labels: RED

#501 Fix: CI frequently failed due to new versions
  pyproject.toml
Labels: BLUE

#502 Fix: Metrics graph not loading due to a "TypeError"
  src/aleph/vm/orchestrator/views/static/helpers.js
Labels: BLUE
